main: me.ksbdude.main.Main
name: IPVP
version: 0.1
description: Crazy pvp plugin
commands:
    join:
        description: joins arena
    createarena:
        description: creates arena
    remove:
        description: removes arena
    leave:
        description: leaves arena
    pvp:
        description: Go to pvp lobby
    setlobby:
        description: leaves arena